dist: xenial

language: c++

before_script:
- sudo add-apt-repository ppa:mhier/libboost-latest -y
- sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
- sudo apt-get update -q
- sudo apt-get install libboost1.70-dev -y
- sudo apt install doxygen -y
- sudo apt install graphviz -y
- sudo apt install cmake-3.15.4 -y
- sudo update-alternatives --install /usr/bin/cmake cmake /usr/bin/cmake-3.15.4 60

script:
- cmake .
- cmake --build .
- cmake --build . --target package

env:
  - TARGET=bayan

deploy:
- provider: pages
  skip-cleanup: true
  local_dir: docs/html
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master

- provider: script
  skip_cleanup: true
  on:
    branch: master
  script:
  - curl -T ${TARGET}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ujohn-jasper-doe:$BINTRAY_API_KEY "https://api.bintray.com/content/john-jasper-doe/otus-cpp/homeworks/${TARGET}/$TRAVIS_BUILD_NUMBER/${TARGET}-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"

